# Generated by Django 4.2.6 on 2023-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_segmento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
