# Generated by Django 4.2.6 on 2023-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('miapp', '0007_alter_evento_segmento_remove_evento_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='segmento',
        ),
        migrations.AddField(
            model_name='evento',
            name='segmento',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
