# Generated by Django 4.2.6 on 2023-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_evento_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
