# Generated by Django 4.2.6 on 2023-11-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_evento_id_alter_evento_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.ManyToManyField(to='miapp.tipo'),
        ),
    ]
